# Generated by Django 4.2.19 on 2025-02-24 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contracts", "0005_alter_contractoragreementdocuments_name_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="contractoragreementdocuments",
            name="display_order",
            field=models.IntegerField(
                default=1,
                help_text="The order in which the documents will be listed. Lower values are displayed first.",
            ),
        ),
        migrations.AlterField(
            model_name="procurementdocuments",
            name="display_order",
            field=models.IntegerField(
                default=1,
                help_text="The order in which the documents will be listed. Lower values are displayed first.",
            ),
        ),
    ]
